### ISSUE TITLE
Source archive hash

### ISSUE THREAD

**Issue by kernelplv** [rosa-abf/rosa-build#32]
![](https://i.imgur.com/t8cfkor.png)

I really miss the ability to view the hash for the source archive. I need this to manually edit yaml, as a developer who does not build the package locally, I have to do it very often.

**Comment by fedya** [comment]
>I need this to manually edit yaml
Ты судя по всему собираешь либо из релиза либо из мастер-бранча.
Тебе не нужно ничего править руками, а нужно освоить имеющиеся инструменты.

В данном случае достаточно выполнить abf put или abb store имя_файла
и **не править** ничего руками.

**Comment by kernelplv** [comment]
Мне для этого понадобится класть свои исходники в архив, я делаю просто git push. Я сам разрабатываю решение, и, к сожалению, приходится его самостоятельно опакечивать.

> > I need this to manually edit yaml
> 
> Ты судя по всему собираешь либо из релиза либо из мастер-бранча.
> Тебе не нужно ничего править руками, а нужно освоить имеющиеся инструменты.
> 
> В данном случае достаточно выполнить abf put или abb store имя_файла
> и **не править** ничего руками.

Не совсем понимаю, как функционал "показа sha" помешает abf.

**Comment by fedya** [comment]
Как по мне это не информативность а просто визуальный мусор.

>Этого всего можно было бы избежать
Всё равно придется копировать и править yml руками.

>приходится совершать лишние телодвижения
Их не придется совершать если один раз настроить свое рабочее место.

тегнем
@DuratarskeyK 
Можно такое сделать?

**Comment by kernelplv** [comment]
> Их не придется совершать если один раз настроить свое рабочее место.

Мое рабочее место отличается от рабочего места сборщика. И для abf-клиента созданного под нужды мейнтейнеров там нет места. Повторюсь, с Александром уже обсуждали это и схема осталась прежней. Однако, если я смогу получать хеш архива с исходниками без скачивания архива с abf с последующим закачиванием его обратно на filestore ради получения сообщения: 
```
sha1_hash '791cae63dag77aeb4355799fbb8e6fbd1879sbed' - file already exists
```
я буду безмерно счастлив.

**Comment by fedya** [comment]
А ты вот эти версии из master-ветки собираешь или как?

**Comment by kernelplv** [comment]
> А ты вот эти версии из master-ветки собираешь или как?

У меня два проекта, каждый имеет версию для import и soft. Собираю тегированные версии, собирал бы из мастера напрямую(раньше так делал), но для проекта 2019.05 это не подходит.

**Comment by fedya** [comment]
вот такие https://abf.io/import/rosa-test-suite/commit/e3009c5f612244b5668c96a2b4258da79efbe6db коммиты ты руками делаешь?

**Comment by kernelplv** [comment]
> вот такие https://abf.io/import/rosa-test-suite/commit/e3009c5f612244b5668c96a2b4258da79efbe6db коммиты ты руками делаешь?

Да. Скачиваю тегированный .tar.gz, закачиваю на filestore, получаю sha, копирую sha в yml и пушу .spec .yml.

**Comment by fedya** [comment]
А по какой причине ты не можешь выполнить
spectool -g *.spec
abf put

Почему нужно обязательно копировать руками хеш для yml?

**Comment by kernelplv** [comment]
> А по какой причине ты не можешь выполнить
> spectool -g *.spec
> abf put
> 
> Почему нужно обязательно копировать руками хеш для yml?

Я попробовал. Во-первых мне нужно устанавливать две дополнительные утилиты: abf-console-client и rpmdevtools. Во-вторых они делают тоже самое, скачивают архив и заливают его обратно. Это лишний трафик и для разработчика и для filestore'а И вместо пуша ветки со спеком, приходится совершать дополнительные действия с дополнительными утилитами, 

Может, можно как-нибудь обойтись без yml вообще? То есть, я пушу проект со спеком, а при сборке, abf сам ищет файл с архивом без генерации yml с моей стороны и без abf put.

**Comment by fedya** [comment]
Без abf.yml и загрузки на файлстор тебе не обойтись никак.
Единственный вариант это сделать автоматику какую-то, как я показал, у себя локально.

**Comment by kernelplv** [comment]
> Без abf.yml и загрузки на файлстор тебе не обойтись никак.
> Единственный вариант это сделать автоматику какую-то, как я показал, у себя локально.

Вот поэтому я и голосую за увеличение гибкости общения с abf в этом ключе :)

**Comment by DuratarskeyK** [comment]
Сделал кнопочку SHA1 в листинге тегов, при нажатии на которую ссылка на сурс превращается в хеш файла сурсов на фсторе.

**Comment by kernelplv** [comment]
> Сделал кнопочку SHA1 в листинге тегов, при нажатии на которую ссылка на сурс превращается в хеш файла сурсов на фсторе.

Да, проверил, это именно то, что нужно. Благодарю!
