### ISSUE TITLE
abf don't send confimation mail

### ISSUE THREAD

**Issue by astrgl** [rosa-abf/rosa-build#39]
Hi, i have update my old mail  the current one. Abf need confirmation for reenable my account but not send any mail for this.

Thank.

astragalo

**Comment by fedya** [comment]
confirmed

**Comment by astrgl** [comment]
Thanks for your help, but keep asking for confirmation.

My user is astragalo ( mail- mauro.carbini@gmail.com)

**Comment by fedya** [comment]
Your accont is confirmed, just try to log in

**Comment by astrgl** [comment]
I'm sorry to bother you again. I believe you did but I get this. 

![abf](https://user-images.githubusercontent.com/83123473/117062690-09d03500-ad24-11eb-8c89-8d7ed8298491.png)

**Comment by fedya** [comment]
ah you talking about not openmandriva abf. right?

**Comment by fedya** [comment]
your screenshot from abf.io/abf.rosalinux.ru
but you registered on abf.openmandriva.org

**Comment by astrgl** [comment]
I am registered in abf-openmandriva and abf-rosalinux.
Abf-openmandriva work fine.

Abf-rosalinux  after the change of mail it asks for confirmation.

Sorry maybe I was not clear.

**Comment by astrgl** [comment]
Thanks now work
