### ISSUE TITLE
дайте возможность после сборки автоматическую публикацию, а то вручную пускать, часто зависает дан

### ISSUE THREAD

**Issue by saber716rus** [rosa-abf/rosa-build#48]

**Comment by saber716rus** [comment]
Здравствуйте. Было бы удобно после сборки автоматическая публикация. Суть в том, что при сборке нужна всё-таки автоматическая публикация, так, как ты всё равно собира

**Comment by fedya** [comment]
Автоматическая публикация после сборки есть. 
Опция у клиента --auto-publish-status

**Comment by saber716rus** [comment]
Понял, спасибо.15:44, 20 декабря 2021 г., Alexander Stefanov ***@***.***>:
Автоматическая публикация после сборки есть.
Опция у клиента --auto-publish-status

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>
С Уважением, Николай.Специалист IT-систем.+79625490833 (whatsapp)telegram: https://t.me/Saber716RUSinstagramm: @saber716russkype: nicksab1491
